module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'blue': {
          50: '#f0f5ff',
          100: '#e5edff',
          500: '#3b82f6',
          600: '#2563eb',
        },
        'indigo': {
          50: '#eef2ff',
          100: '#e0e7ff',
          500: '#6366f1',
          600: '#4f46e5',
        },
      },
      typography: (theme) => ({
        '2xs': {
          css: {
            color: theme('colors.gray.700'),
            maxWidth: 'none',
            fontSize: '0.75rem',
            lineHeight: '1.6',
            'h1, h2, h3, h4, h5, h6': {
              color: theme('colors.gray.900'),
              fontWeight: '700',
              lineHeight: '1.2',
              marginTop: '1.5rem',
              marginBottom: '0.75rem',
              letterSpacing: '-0.025em',
            },
            h1: {
              fontSize: '1.5rem',
              borderBottom: '2px solid #e5e7eb',
              paddingBottom: '0.375rem',
            },
            h2: {
              fontSize: '1.25rem',
              borderBottom: '1px solid #f3f4f6',
              paddingBottom: '0.25rem',
            },
            h3: {
              fontSize: '1.125rem',
              color: theme('colors.gray.700'),
            },
            h4: {
              fontSize: '1rem',
              color: theme('colors.gray.600'),
            },
            p: {
              marginBottom: '1rem',
              lineHeight: '1.6',
              color: theme('colors.gray.700'),
              textAlign: 'left',
            },
            'ul, ol': {
              margin: '1rem 0',
              paddingLeft: '1.25rem',
            },
            li: {
              margin: '0.375rem 0',
              lineHeight: '1.5',
              color: theme('colors.gray.700'),
            },
            'ul li': {
              position: 'relative',
            },
            'ul li::before': {
              content: '"•"',
              color: theme('colors.indigo.500'),
              fontWeight: 'bold',
              position: 'absolute',
              left: '-1rem',
              fontSize: '1.1em',
            },
            'ol li::before': {
              color: theme('colors.indigo.500'),
              fontWeight: '600',
            },
            blockquote: {
              margin: '1rem 0',
              padding: '0.75rem 1rem',
              backgroundColor: '#f8fafc',
              borderLeft: '3px solid #6366f1',
              borderRadius: '0.375rem',
              fontStyle: 'italic',
              color: theme('colors.gray.600'),
              boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
            },
            'blockquote p': {
              margin: '0',
              color: theme('colors.gray.600'),
            },
            code: {
              backgroundColor: '#f1f5f9',
              color: '#1e293b',
              padding: '0.125rem 0.375rem',
              borderRadius: '0.25rem',
              fontSize: '0.75em',
              fontWeight: '500',
              border: '1px solid #cbd5e1',
              fontFamily: 'JetBrains Mono, Fira Code, Monaco, Consolas, monospace',
            },
            pre: {
              backgroundColor: '#1e293b',
              color: '#e2e8f0',
              padding: '1rem',
              borderRadius: '0.5rem',
              overflowX: 'auto',
              border: '1px solid #334155',
              boxShadow: '0 2px 4px -1px rgba(0, 0, 0, 0.1)',
              margin: '1rem 0',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: '0',
              border: 'none',
              fontSize: '0.75rem',
              lineHeight: '1.5',
            },
            strong: {
              color: theme('colors.gray.900'),
              fontWeight: '700',
              backgroundColor: '#fef3c7',
              padding: '0.0625rem 0.1875rem',
              borderRadius: '0.1875rem',
            },
            em: {
              color: theme('colors.gray.600'),
              fontStyle: 'italic',
              fontWeight: '500',
            },
            a: {
              color: theme('colors.indigo.500'),
              textDecoration: 'none',
              borderBottom: '1px solid transparent',
              transition: 'all 0.2s ease',
              fontWeight: '500',
            },
            'a:hover': {
              color: theme('colors.indigo.600'),
              borderBottomColor: theme('colors.indigo.600'),
            },
            hr: {
              border: 'none',
              height: '1px',
              backgroundColor: '#6366f1',
              margin: '1.5rem 0',
              borderRadius: '0.5px',
            },
            table: {
              width: '100%',
              borderCollapse: 'collapse',
              margin: '1rem 0',
              borderRadius: '0.375rem',
              overflow: 'hidden',
              boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)',
            },
            thead: {
              backgroundColor: '#6366f1',
              color: 'white',
            },
            th: {
              padding: '0.75rem',
              textAlign: 'left',
              fontWeight: '600',
              fontSize: '0.75rem',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
            },
            td: {
              padding: '0.75rem',
              borderBottom: '1px solid #e5e7eb',
              color: theme('colors.gray.700'),
            },
            'tbody tr:hover': {
              backgroundColor: theme('colors.gray.50'),
            },
            img: {
              borderRadius: '0.5rem',
              boxShadow: '0 2px 4px -1px rgba(0, 0, 0, 0.1)',
              margin: '1rem auto',
              display: 'block',
              maxWidth: '100%',
              height: 'auto',
            },
          },
        },
        DEFAULT: {
          css: {
            color: theme('colors.gray.700'),
            maxWidth: 'none',
            fontSize: '0.875rem',
            lineHeight: '1.7',
            'h1, h2, h3, h4, h5, h6': {
              color: theme('colors.gray.900'),
              fontWeight: '700',
              lineHeight: '1.3',
              marginTop: '2rem',
              marginBottom: '1rem',
              letterSpacing: '-0.025em',
            },
            h1: {
              fontSize: '1.875rem',
              borderBottom: '2px solid #e5e7eb',
              paddingBottom: '0.5rem',
            },
            h2: {
              fontSize: '1.5rem',
              borderBottom: '1px solid #f3f4f6',
              paddingBottom: '0.375rem',
            },
            h3: {
              fontSize: '1.25rem',
              color: theme('colors.gray.700'),
            },
            h4: {
              fontSize: '1.125rem',
              color: theme('colors.gray.600'),
            },
            p: {
              marginBottom: '1.25rem',
              lineHeight: '1.75',
              color: theme('colors.gray.700'),
              textAlign: 'left',
            },
            'ul, ol': {
              margin: '1.5rem 0',
              paddingLeft: '1.5rem',
            },
            li: {
              margin: '0.5rem 0',
              lineHeight: '1.6',
              color: theme('colors.gray.700'),
            },
            'ul li': {
              position: 'relative',
            },
            'ul li::before': {
              content: '"•"',
              color: theme('colors.indigo.500'),
              fontWeight: 'bold',
              position: 'absolute',
              left: '-1.25rem',
              fontSize: '1.2em',
            },
            'ol li::before': {
              color: theme('colors.indigo.500'),
              fontWeight: '600',
            },
            blockquote: {
              margin: '1.5rem 0',
              padding: '1rem 1.5rem',
              backgroundColor: '#f8fafc',
              borderLeft: '4px solid #6366f1',
              borderRadius: '0.5rem',
              fontStyle: 'italic',
              color: theme('colors.gray.600'),
              boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
            },
            'blockquote p': {
              margin: '0',
              color: theme('colors.gray.600'),
            },
            code: {
              backgroundColor: '#f1f5f9',
              color: '#1e293b',
              padding: '0.25rem 0.5rem',
              borderRadius: '0.375rem',
              fontSize: '0.875em',
              fontWeight: '500',
              border: '1px solid #cbd5e1',
              fontFamily: 'JetBrains Mono, Fira Code, Monaco, Consolas, monospace',
            },
            pre: {
              backgroundColor: '#1e293b',
              color: '#e2e8f0',
              padding: '1.5rem',
              borderRadius: '0.75rem',
              overflowX: 'auto',
              border: '1px solid #334155',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
              margin: '1.5rem 0',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: '0',
              border: 'none',
              fontSize: '0.875rem',
              lineHeight: '1.6',
            },
            strong: {
              color: theme('colors.gray.900'),
              fontWeight: '700',
              backgroundColor: '#fef3c7',
              padding: '0.125rem 0.25rem',
              borderRadius: '0.25rem',
            },
            em: {
              color: theme('colors.gray.600'),
              fontStyle: 'italic',
              fontWeight: '500',
            },
            a: {
              color: theme('colors.indigo.500'),
              textDecoration: 'none',
              borderBottom: '1px solid transparent',
              transition: 'all 0.2s ease',
              fontWeight: '500',
            },
            'a:hover': {
              color: theme('colors.indigo.600'),
              borderBottomColor: theme('colors.indigo.600'),
            },
            hr: {
              border: 'none',
              height: '2px',
              backgroundColor: '#6366f1',
              margin: '2rem 0',
              borderRadius: '1px',
            },
            table: {
              width: '100%',
              borderCollapse: 'collapse',
              margin: '1.5rem 0',
              borderRadius: '0.5rem',
              overflow: 'hidden',
              boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
            },
            thead: {
              backgroundColor: '#6366f1',
              color: 'white',
            },
            th: {
              padding: '1rem',
              textAlign: 'left',
              fontWeight: '600',
              fontSize: '0.875rem',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
            },
            td: {
              padding: '1rem',
              borderBottom: '1px solid #e5e7eb',
              color: theme('colors.gray.700'),
            },
            'tbody tr:hover': {
              backgroundColor: theme('colors.gray.50'),
            },
            img: {
              borderRadius: '0.75rem',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
              margin: '1.5rem auto',
              display: 'block',
              maxWidth: '100%',
              height: 'auto',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('tailwind-scrollbar')({ nocompatible: true }),
  ],
};
